@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Взаимодействие участников и систем в процессе медосмотра

Person_Ext(HR, "Сотрудник кадровой службы предприятия")
Person_Ext(Patient, "Пациент")

System_Ext(EnterpriseSystem, "Предприятие")
System_Ext(RMQ, "Сервер сообщений RabbitMQ")

System_Boundary(Clinic, "МИС IT-Клиника") {
    Container_Boundary(Medosomtr, "Медосмотры") {
        System(ARM, "АРМ председателя врачебной комиссии")
    }
    
}

Rel_D(EnterpriseSystem, HR, "Выдает поручение организовать медосмотр")
Rel_D(HR, RMQ, "Загружает заявки на медосмотр", "AMQP")
Rel(RMQ, ARM, "Передает заявки на медосмотр", "AMQP")

Rel_R(ARM, Patient, "Выдает заключение по результатам медосмотра")
Rel(Patient, HR, "Передает бумажное заключение")

@enduml
