@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


title Взаимодействие участников и систем в процессе медосмотра

Enterprise_Boundary(ExtEnterprise, "Ext Предприятие") {
    Person_Ext(HR, "Сотрудник кадровой службы", "Формирует и отправляет заявки на медосмотр, получает заключение от пациента")
}

Person_Ext(Patient, "Пациент", "Проходит медицинский осмотр и передает заключение кадровой службе")

System_Boundary(Clinic, "IT-Клиника") {
    Container(RMQ, "RabbitMQ", "Сервер сообщений", "Внутренний транспорт обмена заявками на медосмотр")
    Container(ARM, "АРМ председателя врачебной комиссии", "1С:Предприятие", "Рабочее место председателя: просмотр списка пациентов, обработка заявок и оформление заключений")
}

Rel(HR, RMQ, "Передает заявки на медосмотр")
Rel(RMQ, ARM, "Передает данные заявок", "RMQ message")

Rel_R(ARM, Patient, "Выдает заключение по результатам медосмотра")
Rel(Patient, HR, "Передает бумажное заключение")

@enduml
